config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  
  # Move these routes inside the `api` namespace if they are part of your API
  devise_for :users
   root to: 'users#index'
  
  get 'posts/new', to: 'posts#new'
  post 'posts', to: 'posts#create'
  delete 'posts/:id', to: 'posts#destroy', as: :delete_post
  delete 'posts/:post_id/comments/:id', to: 'comments#destroy', as: :delete_comment
  
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show] do
      resources :comments, only: [:create, :new]
      resources :likes, only: [:create]
    end
  end
  
  post 'likes/:post_id', to: 'likes#create'
  post 'comments/:post_id', to: 'comments#create'

  namespace :api do
    namespace :v1 do
      # List all posts for a user

     resources :users, only: [:index, :show] do
      resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    
    end

      # Add a comment to a post
      # post '/posts/:post_id/comments', to: 'posts#create_comment'
  end 
 
  end

end 

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    if user.admin?
      can :manage, :all
    else
      can :read, :all
      can %i[create destroy], Post, author_id: user.id
      can %i[create destroy], Comment, user_id: user.id
    end



    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  validates :text, presence: true

  after_create :update_comments_counter


  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  attribute :comments_counter, :integer, default: 0
  attribute :likes_counter, :integer, default: 0
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  after_create :update_post_counter

  private

  def update_post_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  attribute :posts_counter, :integer, default: 0
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }


  def admin?
    role == 'admin'
  end

  def most_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  protect_from_forgery with: :null_session

  def index
    @comments = Post.find(params[:post_id]).comments
    render json: @comments
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      @comment.update_comments_counter
      render json: @comment, status: :created
    else
      render json: @comment.errors, status: :unprocessable_entity
    end
  end

  private


  def comment_params
    params.require(:comment).permit(:text, :post_id).merge(author_id: params[:user_id])
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  protect_from_forgery with: :null_session

  def index
    @posts = User.find(params[:user_id]).posts
    render json: @posts
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  def index
    @users = User.all
    render json: @users
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |user_params|
      user_params.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @user = current_user
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @comment = current_user.comments.new(comment_params)
    @post = Post.find(params[:post_id])
    @comment.post_id = @post.id
    @comment.save
    flash[:success] = 'Commented!'
    redirect_to posts_path(@post)
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      flash[:success] = 'Comment deleted!'
      @comment.post.decrement!(:comments_counter)
    else
      flash[:danger] = 'Comment not deleted!'
    end
    redirect_to posts_path(@post)
  end



  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def header; end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.new
    @like.post_id = params[:post_id]
    @like.save
    flash[:success] = 'Liked!'
    redirect_to posts_path(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @pagy, @posts = pagy(@user.posts, items: 10)
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:success] = 'Post created!'
      redirect_to "/users/#{current_user.id}/posts"
    else
      flash[:danger] = 'Post not created!'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:success] = 'Post deleted!'
      @post.author.decrement!(:posts_counter)
    else
      flash[:danger] = 'Post not deleted!'
    end
    redirect_to posts_path
  end



  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!


  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/api/v1/comments_helper.rb
module Api::V1::CommentsHelper
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/comments/new.html.erb
<div class="mt-4">
<h3 class="text-lg font-medium mb-2">Add a comment:</h3>
<%= form_for [@post, Comment.new], url: "/comments/#{ @post.id }" do |form| %>
  <%= form.text_area :text, placeholder: "Add comment", class: "w-full rounded-lg p-2 border-gray-300 mb-4 focus:outline-none focus:ring-2 focus:ring-blue-600" %>
  <%= form.submit "Add Comment", class: "bg-blue-600 hover:bg-blue-700 text-white  py-2 px-4 transition-all duration-200" %>
<% end %>
</div>

app/views/home/header.html.erb
<div>
  <h1 class="font-bold text-4xl">Home#header</h1>
  <p>Find me in app/views/home/header.html.erb</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My_Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
 <nav class="bg-blue-600">
  <div class="mx-auto px-4 py-2">
    <div class="flex justify-between">
      <div class="flex items-center">
        <a href="/" class="text-white font-semibold text-lg">My Blog</a>
      </div>
      <div class="flex items-center">
        <ul class="flex">
          <% if current_user %>
            <li><%= link_to "Edit Account", edit_user_registration_path, class: "block px-3 py-2 text-white hover:bg-blue-700" %></li>
            <li><%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "block px-3 py-2 bg-red-600 hover:bg-red-700 text-white font-semibold rounded-lg ml-4" %></li>
          <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path, class: "block px-3 py-2 text-white hover:bg-blue-700"  %></li>
            <li><%= link_to "Sign In", new_user_session_path, class: "block px-3 py-2 text-white hover:bg-blue-700"  %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>
    <main class="container mx-auto mt-28 px-5 ">
     <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/index.html.erb
<div class="bg-white rounded-lg shadow-lg p-6 container mx-auto p-8 flex flex-col gap-8">
  <h1 class="text-3xl font-bold text-center mb-8">List of posts for a given user</h1>

  <div class="flex items-center gap-8">
    <div>
      <img src="<%= @user.photo %>" alt="user photo" class="rounded-full h-24 w-24">
    </div>

    <div class="flex flex-col justify-center">
      <h2 class="text-2xl font-bold leading-tight"><%= @user.name %></h2>
      <div class="flex flex-row gap-4 mt-2">
        <p class="text-gray-500 text-lg font-medium">Number of posts:</p>
        <p class="text-lg font-medium"><%= @user.posts_counter || 0 %></p>
      </div>
    </div>
  </div>

  <section class="mt-8">
    <% @posts.each do |post| %>
    <div class="bg-gray-100 rounded-lg p-6">
      <div class ="flex align-center justify-between">
        <h3 class="text-2xl font-bold mb-4"><%= link_to post.title, "/users/#{@user.id}/posts/#{post.id}", class: "hover:text-blue-500" %></h3>
        <% if  post.author_id == current_user.id || current_user.admin?  %>
        <%= button_to "Delete Post", "/posts/#{post.id}", method: :delete, data: {confirm: "Are you sure you want to delete this post?"}, class: "bg-red-500 text-white px-4 py-2 rounded-lg hover:bg-red-600 transition-all duration-200" %>
        <% end %>
      </div>
    
        <p class="text-gray-700 text-lg leading-relaxed"><%= post.text %></p>

        <div class="flex justify-between items-center mt-8">
          <div>
            <%= form_with url: "/likes/#{post.id}" do |form| %>
              <%= form.submit "Like", class: "bg-blue-500 text-white px-4 py-2 rounded-lg hover:bg-blue-600 transition-all duration-200 mr-2" %>
            <% end %>
        
          </div>

          <div class="text-gray-500 text-lg font-medium">
            <span>Comments: <%= "#{post.comments_counter || 0 }"%></span>
            <span>, Likes: <%= "#{post.likes_counter || 0 }"%></span>
          </div>
        </div>
    </div>

      <div class="bg-gray-50 rounded-lg p-6 mt-4">
        <h4 class="text-xl font-bold mb-4">Comments</h4>
        <% post.most_recent_comments.includes(:author).each do |comment| %>
        <div class ="flex justify-between align-center">
          <div class="flex flex-col gap-1">
            <span class="font-medium"><%= comment.author.name %>:</span>
            <span class="text-gray-700 text-lg leading-relaxed"><%= comment.text %></span>
          </div>
        
           <if comment.author_id == current_user.id || current_user.admin?  %>
            <%= button_to "Delete Comment",delete_comment_path(post_id: post.id, id: comment.id), method: :delete, data: { confirm: "Are you sure you want to delete this comment?" }, class: "bg-white text-red-500 px-4 py-2 rounded-lg hover:bg-red-500 hover:text-white transition-all duration-200 ml-auto border-4 border-red-500" %>
           <% end %>

        </div>
        
      </div>
    <% end %>
  </section>

  <nav class="mt-5 flex justify-center items-center">
  <%== pagy_nav(@pagy) %>
  </nav>
  <div class="flex justify-center mt-12">
    <a href="/posts/new" class="inline-block rounded-lg bg-blue-500 text-white py-3 px-8 hover:bg-blue-600 transition-all duration-200">
      <span class="font-bold text-lg">
        Create new post
      </span>
    </a>
  </div>
</div> 



app/views/posts/new.html.erb
<div class="bg-white rounded-lg shadow-lg p-6 container mx-auto">

  <div>
    <h1 class="text-3xl font-medium mb-4">Create new post</h1>

    <%= form_with model: @post do |form| %>

      <div class="mb-4">
        <%= form.label :title, class: "block font-medium text-gray-700 mb-2" %>
        <%= form.text_field :title, class: "w-full border border-gray-300 rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", placeholder: "Post title" %>
      </div>

      <div class="mb-4">
        <%= form.label :text, class: "block font-medium text-gray-700 mb-2" %>
        <%= form.text_area :text, class: "w-full border border-gray-300 rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", placeholder: "Post text..." %>
      </div>

      <div class="flex items-center justify-center">
        <%= form.submit "Create Post", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      </div>

    <% end %>
  </div>

</div>

app/views/posts/show.html.erb
<div class="bg-white rounded-lg shadow-lg p-6 container mx-auto">
  <h1 class="text-3xl font-medium mb-4">Single post for a given user</h1>
  <h2 class="mb-4">Post #<%= @post.id %> by <%= @user.name %></h2>
  <div class="flex mb-4 text-gray-500 text-sm">
    <span class="mr-4">Comments: <%= @post.comments_counter %></span>
    <span>Likes: <%= @post.likes_counter %></span>
  </div>
  <p class="text-lg mb-4"><%= @post.text %></p>
  <% @post.most_recent_comments.each do |comment| %>
    <div class="flex mb-2">
      <span class="font-medium mr-2"><%= comment.author.name %>:</span>
      <span class="text-gray-500"><%= comment.text %></span>
    </div>
  <% end %>
  <div class="mt-4">
    <h3 class="text-lg font-medium mb-2">Add a comment:</h3>
    <%= form_for [@post, Comment.new], url: "/comments/#{ @post.id }" do |form| %>
      <%= form.text_area :text, placeholder: "Add comment", class: "w-full rounded-lg p-2 border-gray-300 mb-4 focus:outline-none focus:ring-2 focus:ring-blue-600" %>
      <%= form.submit "Add Comment", class: "bg-blue-600 hover:bg-blue-700 text-white py-2 px-4 transition-all duration-200 rounded-lg" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="bg-white rounded-lg shadow-lg container mx-auto p-8">
  <h1 class="text-3xl font-medium text-center mb-4">List of users</h1>
  <% @users.each do |user| %>
    <a href=<%= "users/#{user.id}"%> class="flex items-center gap-4 hover:bg-gray-100 p-4 rounded-lg">
      <%= image_tag(user.photo || "", class: "rounded-full w-12 h-12")%>
      <div class="flex-1">
        <h2 class="text-2xl font-medium text-gray-800"><%= user.name %></h2>
        <span class="text-lg text-gray-500">
          Number of posts: <%= user.posts_counter || 0 %>
        </span>
      </div>
    </a> 
  <% end %>
</div>

app/views/users/show.html.erb
<div class="bg-white rounded-lg shadow-lg p-6 container mx-auto p-8">
  <h1 class="text-3xl font-medium mb-5">Single user</h1>

  <div class="py-4">
    <img src="<%= @user.photo %>" alt="user photo" class="w-32 h-32 rounded-full mx-auto mb-4">
    <h2 class="text-2xl font-medium text-center mb-2"><%= @user.name %></h2>
    <p class="text-xl text-center text-gray-500 mb-6">Number of posts: <span class="text-gray-700"><%= @user.posts_counter %></span></p>
    <div class="text-xl mb-6">
      <h2 class="font-medium">Bio</h2>
      <p><%= @user.bio %></p>
    </div>

    <div class="mt-8">
      <% @user.most_recent_posts.each do |post| %>
        <div class="mb-8">
          <h2 class="font-bold text-2xl mb-2">Post #<%= post.id %></h2>
          <p class="text-xl mb-4"><%= post.text %></p>
          <div class="flex text-gray-500 text-xl">
            <span class="mr-8">Comments: <%= "#{post.comments_counter || 0 }" %></span>
            <span>Likes: <%= "#{ post.likes_counter || 0 }" %></span>
          </div>
        </div>
      <% end %>
    </div>

    <div class="flex justify-center mt-8">
      <div class="p-2 bg-blue-500 rounded">
        <a href="/users/<%= @user.id %>/posts" class="text-white font-semibold">
          See All Posts
        </a>
      </div>
    </div>
  </div>
</div>